apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wildwest-shooter.fullname" . }}-{{ .Values.name.backend }}
  labels:
    {{- include "wildwest-shooter.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: {{ .Chart.Name  }}
spec:
  replicas: {{ .Values.replicaCountBackend }}
  selector:
    matchLabels:
      {{- include "wildwest-shooter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wildwest-shooter.selectorLabels" . | nindent 8 }}
        role: {{ .Values.name.backend }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "wildwest-shooter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.backend }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /egg
              port: http
          readinessProbe:
            httpGet:
              path: /egg
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
